name: Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest test-app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH and deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.BACKEND_SSH_HOST }}
        EC2_USER: ${{ secrets.BACKEND_USER_NAME }}
        APP_DIR: /home/ubuntu/parcial-backend
      run: |
        echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ec2_key
        chmod 600 ec2_key
        ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
            # Acceder al directorio del proyecto
            cd parcial-backend &&

            # Activar el entorno virtual si es necesario
            source env/bin/activate &&

            # Sincronizar los últimos cambios del repositorio
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&

            # Instalar dependencias necesarias
            pip install -r requirements.txt &&
            
            # Detener instancias previas de Gunicorn si existen
            pkill gunicorn || true

            # Ejecuta la aplicación con Gunicorn
            gunicorn -b 0.0.0.0:5000 main_app:app --daemon
        '
